# Generated by Django 3.2.5 on 2022-04-07 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HP', models.IntegerField(blank=True)),
                ('Atk', models.IntegerField(blank=True)),
                ('Def', models.IntegerField(blank=True)),
                ('SpA', models.IntegerField(blank=True)),
                ('SpD', models.IntegerField(blank=True)),
                ('Spe', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Iv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HP', models.IntegerField(blank=True)),
                ('Atk', models.IntegerField(blank=True)),
                ('Def', models.IntegerField(blank=True)),
                ('SpA', models.IntegerField(blank=True)),
                ('SpD', models.IntegerField(blank=True)),
                ('Spe', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('update', models.DateTimeField(auto_now=True, verbose_name='date_published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('nickName', models.CharField(blank=True, max_length=200, null=True)),
                ('shiny', models.BooleanField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=200, null=True)),
                ('item', models.CharField(blank=True, max_length=200, null=True)),
                ('ability', models.CharField(blank=True, max_length=200, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('nature', models.CharField(blank=True, max_length=200, null=True)),
                ('moves1', models.CharField(blank=True, max_length=200, null=True)),
                ('moves2', models.CharField(blank=True, max_length=200, null=True)),
                ('moves3', models.CharField(blank=True, max_length=200, null=True)),
                ('moves4', models.CharField(blank=True, max_length=200, null=True)),
                ('evs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teambuilding.ev')),
                ('ivs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teambuilding.iv')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teambuilding.team')),
            ],
        ),
    ]
