# Generated by Django 3.2.5 on 2022-04-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teambuilding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ev',
            name='Atk',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='ev',
            name='Def',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='ev',
            name='HP',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='ev',
            name='SpA',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='ev',
            name='SpD',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='ev',
            name='Spe',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='iv',
            name='Atk',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='iv',
            name='Def',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='iv',
            name='HP',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='iv',
            name='SpA',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='iv',
            name='SpD',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='iv',
            name='Spe',
            field=models.FloatField(blank=True),
        ),
    ]
