# Generated by Django 3.2.5 on 2022-01-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teambuilding', '0002_team_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
