# Generated by Django 3.2.5 on 2022-04-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teambuilding', '0002_auto_20220417_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
