# Generated by Django 3.2.5 on 2022-02-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teambuilding', '0003_alter_team_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='date_published'),
        ),
    ]
